version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: terraform_dashboard
      POSTGRES_USER: terraform_indexer
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U terraform_indexer -d terraform_dashboard"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - terraform-dashboard

  terraform-indexer:
    build:
      context: .
      dockerfile: terraform-indexer/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - CONFIG_FILE=/app/config.yaml
    volumes:
      - ./terraform-indexer/config.yaml:/app/config.yaml:ro
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - terraform-dashboard
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  terraform-dashboard:
    driver: bridge